name: Orquestador CERT

on:
  repository_dispatch:
    types: [jira-orquestador-certificacion]
  workflow_dispatch:
    inputs:
      issue_key:
        description: "Clave del ticket de Jira"
        required: true
      branch_name:
        description: "Rama asociada al ticket"
        required: true

permissions:
  contents: write

jobs:
  run-cert-workflows:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lanzar workflow de congelamiento
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          ISSUE_KEY: ${{ github.event.inputs.issue_key || github.event.client_payload.issue_key }}
          BRANCH_NAME: orquestador/${{ github.event.inputs.issue_key || github.event.client_payload.issue_key }}
        run: |
          echo "ðŸ“Œ ISSUE_KEY: $ISSUE_KEY"
          echo "ðŸŒ¿ BRANCH_NAME: $BRANCH_NAME"

          echo "ðŸš€ Disparando workflow de congelamiento en la rama $BRANCH_NAME para el issue $ISSUE_KEY ..."
          curl -i -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/ricardops2211/orquestador-github/dispatches \
            -d "{joborquestador-cert
                  \"event_type\": \"joborquestador-cert\",
                  \"client_payload\": {
                    \"issue_key\": \"$ISSUE_KEY\",
                    \"branch_name\": \"$BRANCH_NAME\"
                  }
                }"

